In [1]:
import numpy as np

In [2]:
import pandas as pd

In [20]:
index = [1,2,3,4,5]

In [ ]:
from numpy.random import randn

In [9]:
data = ['sahil','sapana','sanjay','aayush']

In [10]:
ser = pd.Series(data,index)

In [11]:
print(ser)

1     sahil
2    sapana
3    sanjay
4    aayush
dtype: object


In [13]:
tmp1 = np.random.randn(5,4)

In [14]:
print(tmp1)

[[-1.26704728 -0.92273658 -0.58784452  1.49441949]
 [ 0.48410748 -0.15242503 -0.21744093  0.2273898 ]
 [-1.09502012  0.18001151  0.92192424  0.28624366]
 [-0.78031275  0.59435963 -0.44247417  1.37846204]
 [-0.20546748  0.18964497 -0.01424964 -1.84196562]]


In [15]:
np.random.seed(101)

In [21]:
tmp2 = np.random.randn(5,5)

In [22]:
print(tmp2)

[[ 3.02665449e-01  1.69372293e+00 -1.70608593e+00 -1.15911942e+00
  -1.34840721e-01]
 [ 3.90527843e-01  1.66904636e-01  1.84501859e-01  8.07705914e-01
   7.29596753e-02]
 [ 6.38787013e-01  3.29646299e-01 -4.97104023e-01 -7.54069701e-01
  -9.43406403e-01]
 [ 4.84751647e-01 -1.16773316e-01  1.90175480e+00  2.38126959e-01
   1.99665229e+00]
 [-9.93263500e-01  1.96799505e-01 -1.13664459e+00  3.66479606e-04
   1.02598415e+00]]


In [23]:
df1 = pd.DataFrame(tmp2,index,index)

In [24]:
print(df1)

          1         2         3         4         5
1  0.302665  1.693723 -1.706086 -1.159119 -0.134841
2  0.390528  0.166905  0.184502  0.807706  0.072960
3  0.638787  0.329646 -0.497104 -0.754070 -0.943406
4  0.484752 -0.116773  1.901755  0.238127  1.996652
5 -0.993263  0.196800 -1.136645  0.000366  1.025984
