# Tensorflow-2.0 in Action 

> TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices.
> Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

## Installation of Tensorflow

>TensorFlow is tested and supported on the following 64-bit systems:

>1.Ubuntu 16.04 or later

>2.Windows 7 or later

>3.macOS 10.12.6 (Sierra) or later (no GPU support)

>4.Raspbian 9.0 or later

> **pip install tensorflow==2.0.0**

> To run from Anaconda Prompt

> **!pip install tensorflow==2.0.0**

> To run from Jupyter Notebook

`Both Tensorflow 2.0 and Keras have been released for four years (Keras was released in March 2015, and Tensorflow was released in November of the same year). The rapid development of deep learning in the past days, we also know some problems of Tensorflow1.x and Keras:`

* Using Tensorflow means programming static graphs, which is difficult and inconvenient for programs that are familiar with imperative programming

* Tensorflow api is powerful and flexible, but it is more complex, confusing and difficult to use.

* Keras api is productive and easy to use, but lacks flexibility for research


#### Version Check

In [2]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

TensorFlow version: 2.4.1
Keras version: 2.4.0


`Tensorflow2.0 is a combination design of Tensorflow1.x and Keras. Considering user feedback and framework development over the past four years, it largely solves the above problems and will become the future machine learning platform.`

> Tensorflow 2.0 is built on the following core ideas:


* The coding is more pythonic, so that users can get the results immediately like they are programming in numpy
* Retaining the characteristics of static graphs (for performance, distributed, and production deployment), this makes TensorFlow fast, scalable, and ready for production.
* Using Keras as a high-level API for deep learning, making Tensorflow easy to use and efficient
* Make the entire framework both high-level features (easy to use, efficient, and not flexible) and low-level features (powerful and scalable, not easy to use, but very flexible)

>Eager execution is by default in TensorFlow 2.0 and, it needs no special setup.
>The following below code can be used to find out whether a CPU or GPU is in use

### GPU/CPU Check

In [2]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


### Tensor Constant

In [3]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [4]:
ineuron.numpy()

AttributeError: 'Tensor' object has no attribute 'numpy'

In [5]:
ineuron1 = tf.constant(1, dtype = tf.int64)
ineuron1

<tf.Tensor 'Const_1:0' shape=() dtype=int64>

In [6]:
ineuron_x = tf.constant([[4,2],[9,5]])
print(ineuron_x)

Tensor("Const_2:0", shape=(2, 2), dtype=int32)


In [8]:
ineuron_x.numpy()

AttributeError: 'Tensor' object has no attribute 'numpy'

In [9]:
print('shape:',ineuron_x.shape)
print(ineuron_x.dtype)

shape: (2, 2)
<dtype: 'int32'>


#### Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [10]:
print(tf.ones(shape=(2,3)))

Tensor("ones:0", shape=(2, 3), dtype=float32)


In [11]:
print(tf.zeros(shape=(3,2)))

Tensor("zeros:0", shape=(3, 2), dtype=float32)


In [12]:
const2 = tf.constant([[3,4,5], [3,4,5]]);tf
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result)

Tensor("Add:0", shape=(2, 3), dtype=int32)


>We have defined two constants and we add one value to the other. 
>As a result, we got a Tensor object with the result of the adding. 

#### Random constant

In [13]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor 'random_normal:0' shape=(2, 2) dtype=float32>

In [14]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor 'random_uniform:0' shape=(2, 2) dtype=int32>

### Variables

>A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

#### Declaring variables

In [15]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_2:0' shape=(2, 2, 3) dtype=float32_ref>)

>TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

#### The datatype can be explicitly specified

In [16]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64_ref

`TensorFlow has a large number of built-in datatypes.`
* tf.float16: 16-bit half-precision floating-point.
* tf.float32: 32-bit single-precision floating-point.
* tf.float64: 64-bit double-precision floating-point.
* tf.bfloat16: 16-bit truncated floating-point.
* tf.complex64: 64-bit single-precision complex.
* tf.complex128: 128-bit double-precision complex.
* tf.int8: 8-bit signed integer.
* tf.uint8: 8-bit unsigned integer.
* tf.uint16: 16-bit unsigned integer.
* tf.uint32: 32-bit unsigned integer.
* tf.uint64: 64-bit unsigned integer.
* tf.int16: 16-bit signed integer.
* tf.int32: 32-bit signed integer.
* tf.int64: 64-bit signed integer.
* tf.bool: Boolean.
* tf.string: String.
* tf.qint8: Quantized 8-bit signed integer.
* tf.quint8: Quantized 8-bit unsigned integer.
* tf.qint16: Quantized 16-bit signed integer.
* tf.quint16: Quantized 16-bit unsigned integer.
* tf.qint32: Quantized 32-bit signed integer.
* tf.resource: Handle to a mutable resource.
* tf.variant: Values of arbitrary types.


#### To reassign a variable, use var.assign()

In [17]:
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable_4:0' shape=() dtype=float32_ref>

In [18]:
var_reassign.assign(98.)
var_reassign

<tf.Variable 'Variable_4:0' shape=() dtype=float32_ref>

In [19]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable_5:0' shape=(2, 2) dtype=float32_ref>


>We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [20]:
new_value = tf.random.normal(shape=(2, 2))
# a.assign(new_value)
# print(a.numpy())
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j] # This thing dosen't work. I don't know why Ineuron has put this in their training notebook.
new_value,a

AssertionError: 

In [21]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

AssertionError: 

#### Shaping a tensor

In [16]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


#### Tensors can be reshaped and retain the same values which is required for constructing Neural networks.

In [17]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [18]:
tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

### Rank of a tensor

>The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor.

In [24]:
tf.rank(tensor)

<tf.Tensor: id=202, shape=(), dtype=int32, numpy=3>

>(the shape is () because the output here is a scalar value)

#### Specifying an element of a tensor

In [19]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

#### Casting a tensor to a NumPy variable

In [26]:
print(tensor.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [27]:
print(tensor[1, 0, 2].numpy())

18.0


#### Finding the size or length of a tensor

In [28]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [29]:
#the datatype of a tensor
tensor3.dtype

tf.float32

### Tensorflow mathematical operations
>Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.


In [30]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-0.56271744 -0.55164266]
 [ 0.27730447  0.43937662]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.46430582  2.074887  ]
 [ 0.6814727  -0.03568114]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.09841162  1.5232444 ]
 [ 0.9587772   0.40369546]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.00968485 2.3202734 ]
 [0.9192537  0.16297002]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.90627575 4.5870833 ]
 [2.608505   1.497348  ]], shape=(2, 2), dtype=float32)


In [14]:
aa,ab = tf.Variable(2),tf.Variable(7)
aa**ab

<tf.Tensor: shape=(), dtype=int32, numpy=128>

### Performing element-wise primitive tensor operations

In [31]:
tensor*tensor

<tf.Tensor: id=233, shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

### Broadcasting in Tensorflow

>Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

>The simplest example is multiplication of  a tensor by a scalar value.

In [32]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


### Transpose Matrix multiplication

In [33]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: id=241, shape=(1, 1), dtype=int32, numpy=array([[64]])>

### Casting a tensor to another datatype

In [34]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: id=242, shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])>

In [28]:
t = tf.constant(tensor1,dtype=tf.int32)
t

TypeError: Expected tensor with type tf.int32 not tf.float32

In [29]:
t = tf.constant(tensor1.numpy(),dtype=tf.int32)
t

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])>

##### Casting with truncation

In [35]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: id=244, shape=(), dtype=int32, numpy=4>

###  Ragged tensors

`A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.`

#### Below example shows how to declare a constant ragged array

In [36]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


### Squared difference of tensors

In [34]:
varx = [4,5,6,1,2]
varxx = [4,15,6,1,-3]
vary = 8
varz = tf.math.squared_difference(varx,varxx)
varzz = tf.math.squared_difference(varx,vary) 
varz,varzz

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([  0, 100,   0,   0,  25])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>)

#### Calculate the mean

>Function available
>tf.reduce_mean().

`Similar to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type`

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`

In [38]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])

#### Calculate the mean across all axes

In [39]:
tf.reduce_mean(input_tensor=numbers) #default axis = None

<tf.Tensor: id=377, shape=(), dtype=float32, numpy=5.0>

#### Calculate the mean across columns (reduce rows) with this:

In [40]:
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: id=379, shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

#### When keepdims = True

In [41]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: id=381, shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

#### Calculate the mean across rows (reduce columns) with this:

In [42]:
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: id=383, shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

#### When keepdims= True

In [43]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: id=385, shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

####  Random values generation

##### tf.random.normal()

>tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

>The function is as follows:
    
`tf.random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)`

In [44]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)
randon_num = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(randon_num)

tf.Tensor(
[[13.419874  9.652067]
 [ 8.206388 10.20897 ]
 [ 9.400301  9.270695]], shape=(3, 2), dtype=float32)


####  tf.random.uniform()

>The function is this:
    
>tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)

`This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound isn't.

Example:`

In [45]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: id=404, shape=(2, 4), dtype=float32, numpy=
array([[0.4859345 , 0.667521  , 0.28568578, 0.86824465],
       [0.28643095, 0.81876636, 0.6277267 , 0.8998866 ]], dtype=float32)>

#### Setting the seed

In [46]:
tf.random.set_seed(11)
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 1
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [47]:
tf.random.set_seed(11) #same seed
random_num1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
random_num2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(random_num1) #Call 2
print(random_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### Practical example of Random values using Dices

In [48]:
dice11 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice12 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

# lets ADD
dice_sum1 = dice11 + dice12
# We've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.
finale_matrix = tf.concat(values=[dice11, dice12, dice_sum1], axis=1)
print(finale_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


#### Finding the indices of the largest and smallest element

>The following functions are available:
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`

In [49]:
# 1-D tensor
tensor_1d = tf.constant([12, 11, 51, 42, 6, 16, -8, -19, 31])
print(tensor_1d)


i = tf.argmax(input=tensor_1d)
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())


i = tf.argmin(input=tensor_1d,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',tensor_1d[i].numpy())

tf.Tensor([ 12  11  51  42   6  16  -8 -19  31], shape=(9,), dtype=int32)
index of max;  tf.Tensor(2, shape=(), dtype=int64)
Max element:  51
index of min:  7
Min element:  -19


#### Saving and restoring using a checkpoint

In [36]:
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
print(variable1)
checkpoint= tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./ckeckpt/vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
print(variable1)
checkpoint.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]])>


#### Using tf.function

`tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.`


>Its function is as follows:
    
`tf.function(
func=None,input_signature=None,autograph=True,experimental_autograph_options=None
)`


In [41]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)
func = tf.function(f1)
x = tf.constant([3., -4.])
y = tf.constant([1., 4.])
# f1 and func return the same value, but func executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()
#The assert passes, so there is no output

In [42]:
f1(x,y).numpy() == func(x,y).numpy()

True

In [44]:
f1(x,y),func(x,y)

(<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-78.5>)

## Calculate the gradient

### GradientTape

>Another difference from numpy is that it can automatically track the gradient of any variable.

>Open one GradientTape and `tape.watch()` track variables through

In [52]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


>For all variables, the calculation is tracked by default and used to find the gradient, so do not use `tape.watch()`

In [53]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


> You can GradientTapefind higher-order derivatives by opening a few more:

In [54]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.4264985  0.6867533 ]
 [0.44663432 0.5015956 ]], shape=(2, 2), dtype=float32)
