In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.4.0
Keras version: 2.4.0


In [2]:
variable = tf.Variable([3, 3])
if tf.config.list_physical_devices('GPU'):
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


In [3]:
tf.config.list_physical_devices('GPU')

[]

In [6]:
sahil = tf.constant('sahil')
num = tf.constant(1729)

In [15]:
type(sahil)

tensorflow.python.framework.ops.EagerTensor

In [16]:
num

<tf.Tensor: shape=(), dtype=int32, numpy=1729>

In [17]:
type(num)

tensorflow.python.framework.ops.EagerTensor

In [18]:
num?

Type:            EagerTensor
String form:     tf.Tensor(1729, shape=(), dtype=int32)
File:            c:\users\magic\anaconda3\envs\dl1\lib\site-packages\tensorflow\python\framework\ops.py
Docstring:       <no docstring>
Class docstring: Base class for EagerTensor.


In [20]:
sahil.numpy(),num.numpy()

(b'sahil', 1729)

>> - As you can see in Tensorflow 2.X we can directly obtain the value without creating an session uilike in Tensorflow 2.X

In [21]:
print(sahil.dtype)
print(sahil.shape)
print(num.dtype)
print(num.shape)

<dtype: 'string'>
()
<dtype: 'int32'>
()


In [22]:
print(tf.zeros(shape=(3,2)))
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [28]:
const2 = tf.constant([[3,4,5], [3,4,5]]);
const1 = tf.constant([[1,2,3], [1,2,3]]);
result = tf.add(const1, const2);
print(result,'\n\n',result.shape)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32) 

 (2, 3)


In [29]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 5],
       [5, 8]])>

In [35]:
tf.random.normal(shape=(2,2),mean=0,stddev=9.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ -6.4791007 ,   0.86386526],
       [-12.447509  , -18.267082  ]], dtype=float32)>

In [36]:
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var1, var2

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [50]:
type(var2)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

>> - * * * *  The datatype can be explicitly specified

In [62]:
int_const = tf.constant(1, dtype = tf.int64)
float_var64 = tf.Variable(89, dtype = tf.float64)
int_const,float_var64

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>)

### Also we do not have the concept of placeholder in TF 2.X

`TensorFlow has a large number of built-in datatypes.`
* tf.float16: 16-bit half-precision floating-point.
* tf.float32: 32-bit single-precision floating-point.
* tf.float64: 64-bit double-precision floating-point.
* tf.bfloat16: 16-bit truncated floating-point.
* tf.complex64: 64-bit single-precision complex.
* tf.complex128: 128-bit double-precision complex.
* tf.int8: 8-bit signed integer.
* tf.uint8: 8-bit unsigned integer.
* tf.uint16: 16-bit unsigned integer.
* tf.uint32: 32-bit unsigned integer.
* tf.uint64: 64-bit unsigned integer.
* tf.int16: 16-bit signed integer.
* tf.int32: 32-bit signed integer.
* tf.int64: 64-bit signed integer.
* tf.bool: Boolean.
* tf.string: String.
* tf.qint8: Quantized 8-bit signed integer.
* tf.quint8: Quantized 8-bit unsigned integer.
* tf.qint16: Quantized 16-bit signed integer.
* tf.quint16: Quantized 16-bit unsigned integer.
* tf.qint32: Quantized 32-bit signed integer.
* tf.resource: Handle to a mutable resource.
* tf.variant: Values of arbitrary types.


>> - * * * * To reassign a variable, use var.assign()

In [63]:
float_var64.assign(9)

<tf.Variable 'UnreadVariable' shape=() dtype=float64, numpy=9.0>

In [64]:
float_var64.numpy()

9.0

In [65]:
int_const.assign(5) # you cannot reassign an constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [76]:
fltvar = 88
assert float_var64 == fltvar

AssertionError: 

In [85]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.08750866,  0.5964444 ],
       [-0.60231096,  1.0015047 ]], dtype=float32)>

In [86]:
initial_value2 = tf.random.normal(shape=(3,4))
a.assign(initial_value2)
a

ValueError: Cannot assign to variable Variable:0 due to variable shape (2, 2) and value shape (3, 4) are incompatible

In [87]:
b = tf.Variable([1,2,3,4])
b.assign([1,2,3])

ValueError: Cannot assign to variable Variable:0 due to variable shape (4,) and value shape (3,) are incompatible

In [88]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [89]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.123928  ,  0.47403353],
       [ 0.7810433 , -0.7755123 ]], dtype=float32)>